### ISSUE TITLE
Knobs

### ISSUE THREAD

**Issue by extremenerble** [TOILmodular/GHOST_IN_THE_MACHINE#1]
What is the diameter of the knobs you use? They look like 20mm, but I'm just guessing.

Thank you!

**Comment by HeitorAL9000** [comment]
I've used 15mm ones 
![Uploading IMG_0354 2.JPG…]()

**Comment by TOILmodular** [comment]
Actually, I am using knobs with 16mm diameter. 
https://akizukidenshi.com/catalog/g/g100253/ 
(sorry, inJapanese)
